# Site settings
title: pra.gov

# Build settings
scripts:
  - assets/uswds/js/uswds.min.js

styles:
  - assets/uswds/css/styles.css

exclude:
  - _scss
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - node_modules
  - package-lock.json
  - package.json
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

keep_files:
  - assets/uswds
